baseurl = "http://localhost:1313/"
languageCode = "en-us"
title = "czrpc documentation"
theme = "hugo-theme-learn"
metaDataFormat= "toml"

[params]
  # Hugo-theme-learn parameters
  
  # Prefix URL to edit current page. Useful to give opportunity to people to create merge request for your doc.
  # See the config.toml file from this documentation site to have an example.
  editURL = ""
  # Author of the site, will be used in meta information
  author = "Rui Figueira"
  # Description of the site, will be used in meta information
  description = "Documentation for the czrpc library"
  # Shows a checkmark for visited pages on the menu. Default to false
  showVisitedLinks = false

